---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-external-ingress-proxy-config
  namespace: cluster-services
data:
  traefik.toml: |-
    defaultEntryPoints = ["http", "https"]
    [entryPoints]
      [entryPoints.http]
        address = ":80"
        compress = true
      [entryPoints.http.redirect]
        entryPoint = "https"
      [entryPoints.https]
        address = ":443"
      [entryPoints.https.tls]
    [acme]
      email = "hostmaster@your-domain"
      storage = "/traefik/acme/account"
      entryPoint = "https"
      onHostRule = true
      acmeLogging = true
      caServer = "https://acme-v02.api.letsencrypt.org/directory"
      #caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
      [acme.httpChallenge]
        entryPoint = "http"
    [etcd]
      endpoint = "traefik-etcd-cluster-client.etcd-operator:2379"
      useAPIV3 = true
---
apiVersion: batch/v1
kind: Job
metadata:
  name: traefik-etcd-config
  namespace: cluster-services
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 100
  template:
    metadata:
      name: traefik-etcd-config
    spec:
      containers:
      - name: storeconfig
        image: traefik:alpine
        imagePullPolicy: IfNotPresent
        command: ["traefik"]
        args: [ "storeconfig", "-c", "/etc/traefik/traefik.toml", "--etcd.endpoint=etcd-cluster-client.etcd-operator:2379", "--etcd.useAPIV3=true", "--etcd.prefix=/traefik"]
        volumeMounts:
        - name: config
          mountPath: /etc/traefik
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: traefik-external-ingress-proxy-config
